title: The FIPS Wall of Shame
description: A list of vendors who treat FIPS cryptography as a luxury feature, not a core security requirement.

url: https://jscholefield.github.io/fips-tax-wall-of-shame

theme: jekyll-theme-cayman
kramdown:
  parse_block_html: true

collections:
  - vendors
